project_id = "gcwtrscvdteidwdusoee"

[functions.generate-storyboard]
verify_jwt = false

[functions.recommend-music]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false

[functions.render-video]
verify_jwt = false

[functions.check-render-status]
verify_jwt = false

[functions.render-remotion]
verify_jwt = false

[functions.remotion-webhook]
verify_jwt = false

[functions.check-remotion-status]
verify_jwt = false